### ISSUE TITLE
Expectations For Mentors

### ISSUE THREAD

**Issue by yaahc** [RustBeginners/awesome-rust-mentors#1]
We need to properly fill out the expectations. I'm thinking the following points are important to include.

* The main goal is to help them get involved in rust, not to directly teach them. Guiding them to resources and answering questions or helping them find the answer, not giving structured lessons.
* Be polite and always constructive
* Its okay if you don't have a ton of time, as long as you're responsive within ~ 1 day of a question (is this reasonable?)
* If you're no longer active please ask to be removed.

There's probably a ton more things that should be said.

**Comment by sorenmortensen** [comment]
> responsive within ~ 1 day of a question (is this reasonable?)

Personally I think this is reasonable, as long as a "response" is understood to mean some kind of reply, including a reply such as "having a busy few days, I will get back to you on __ day"

**Comment by yaahc** [comment]
This comment applies to both this and #11 but I'm worried about some people having misconceptions over payment. Worst case scenario I'm worried about getting a mentor who asks their mentee's for payment for services. On the other side, I don't know if it would be okay or not for the mentee to ask to pay for tutoring specifically instead of mentoring.

If there are a large group of people who are specifically interested in tutoring though it might be worth setting up a awesome-rust-tutors list, but that seems like its ripe for abuse.

**Comment by RadicalZephyr** [comment]
I think re: mentoring vs tutoring it makes sense for this list to say explicitly that these people are volunteers and this is not a paid service.  Any agreement that individual mentors want to make to do paid tutoring can be considered directly between a mentor and a mentee.
