### ISSUE TITLE
me me me :P

### ISSUE THREAD

**Issue by Dylan-DPC** [RustBeginners/awesome-rust-mentors#103]
Preferred Name: Dylan DPC

Github Handle: Dylan DPC

Pronouns: he/him 

Contact: Discord (@dpc), Twitter (@dpc_22)

Spoken Languages: **English**, German (will be fun xD)

Topics: Open to anything that is sort of in the general-purpose domain 
\

**Comment by dpc** [comment]
@Dylan-DPC We should get a coffee one day. :wave:

**Comment by Dylan-DPC** [comment]
Oh lol xD yah sure 😄
