### ISSUE TITLE
Add @mystal as a mentor

### ISSUE THREAD

**Issue by mystal** [RustBeginners/awesome-rust-mentors#105]
### Gabe Martinez ([@mystal](https://github.com/mystal))
* **Pronouns**: they/them
* **Contact**: Twitter ([@mystalice](https://twitter.com/mystalice)), Discord (mystal#3600)
* **Spoken Languages**: English
* **Topics**: Beginner/Intermediate Rust, Game Programming (& Design), Rapid Prototyping, Product Management

**Comment by mystal** [comment]
Hooray!! Thanks! :tada:

**Comment by yaahc** [comment]
my pleasure! thank you for helping out
