### ISSUE TITLE
Expectations for Mentees

### ISSUE THREAD

**Issue by yaahc** [RustBeginners/awesome-rust-mentors#11]
* Remember that these mentors are a 100% volunteer group, be kind and courteous.
* Something about mentoring vs tutoring, maybe unnecessary as repetative from mentor section?
* Please inform us if they're non responsive for a long period (7 days with no explanation?) or violate the CoC in any way. (need a point of contact for the repo that is not public, if someone experiences abuse we don't want them to have to open an issue to report it.)

I dont know what else

**Comment by RadicalZephyr** [comment]
Maybe some language that mirrors the point in #1 about getting involved and giving pointers to resources versus directly teaching to help set expectations about what kind of help they will receive?
