### ISSUE TITLE
Add anchors to the `awesome-rust-mentors` website so people can link directly to specific mentors

### ISSUE THREAD

**Issue by yaahc** [RustBeginners/awesome-rust-mentors#151]

**Comment by zevaverbach** [comment]
@yaahc I assume you'd accept a JS-based implementation of this? Kramdown, the markdown processor used by default by Jekyll, is already creating IDs for all the `h3`s but there's no programmatic way of accessing those IDs in the markdown itself, I don't think.

**Comment by yaahc** [comment]
> @yaahc I assume you'd accept a JS-based implementation of this?

absolutely! :+1:

**Comment by jyn514** [comment]
I think this has been done :) e.g. https://rustbeginners.github.io/awesome-rust-mentors/#jane-losare-lusby-yaahc
