### ISSUE TITLE
Projects page is malformed

### ISSUE THREAD

**Issue by alice-i-cecile** [RustBeginners/awesome-rust-mentors#174]
[This page](https://github.com/RustBeginners/awesome-rust-mentors/blob/master/_includes/projects.md) has what appears to be a HTML tag that's showing up on the preview.

> <script> var people = []; var e = document.getElementById("project-mentorship"); while (e.nextSibling.nodeName != 'H3') e.nextSibling.remove(); e = e.nextSibling; do { let person = []; do { person.push(e); e = e.nextSibling; } while (!/^H[123]$/i.test(e.nodeName)); people.push(person); } while (e.nodeName == 'H3'); for (let i = people.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [people[i], people[j]] = [people[j], people[i]]; } people.forEach(person => { person.forEach(x => { e.parentNode.insertBefore(x, e); }); }); e.remove(); </script>

**Comment by yaahc** [comment]
That's an artifact of how we render the page via jekyll. Those are meant to shuffle the order of the projects and mentors on https://rustbeginners.github.io/awesome-rust-mentors/, but github's md render doesn't have the same JS support. If there's a good way to separate the js from these md docs but still get the functionality in the final webpage I'd happily merge a PR updating the code, but we already have some less than ideal `{ % include % }` sections on the main readme page which I don't think we can get rid of so I'm not sure if it's worth putting effort into.
