### ISSUE TITLE
Update my info

### ISSUE THREAD

**Issue by kpp** [RustBeginners/awesome-rust-mentors#178]
### Roman ([@kpp](https://github.com/kpp))
* **Contact**: Telegram (gitkpp)
* **Spoken Languages**: English, Russian
* **Topics**: Beginner/Intermediate Rust, async, futures, CI
* **Timezone**: Yerevan (GMT+4)

**Comment by yaahc** [comment]
Hey, would it be possible to submit this as a PR?
