### ISSUE TITLE
Add Lucio as a mentor

### ISSUE THREAD

**Issue by LucioFranco** [RustBeginners/awesome-rust-mentors#2]
* **Github Username or equivalent handle**: @LucioFranco
* **Pronouns**: He/Him
* **Contact**: twitter [@lucio_d_franco](https://twitter.com/lucio_d_franco)
* **Spoken Languages**: English, Italian, French
* **Topics**: async io, networking, distributed systems, game dev, compilers

lmk if there is anything else!

**Comment by yaahc** [comment]
Because your handle is your name I'm gonna assume its safe to put your full name followed by a link to your github username, like in my bio.

**Comment by LucioFranco** [comment]
@yaahc sure whatever you think is good! Full name is everywhere anyways!

**Comment by yaahc** [comment]
Sounds good! Done.
