### ISSUE TITLE
Add Bhargav as mentor

### ISSUE THREAD

**Issue by bIgBV** [RustBeginners/awesome-rust-mentors#27]
### Bhargav Voleti ([@bIgBV](https://github.com/bIgBV))
* **Pronouns**: he/him
* **Contact**: Twitter ([@2093bps](https://twitter.com/2093bps))
* **Spoken Languages**: _English_, Hindi
* **Topics**: Beginners, async, distributed systems

**Comment by yaahc** [comment]
Did you have a language you would prefer to emphasize? We've been italicizing everyone's first language.

**Comment by bIgBV** [comment]
Sure thing let me just update the issue.
