### ISSUE TITLE
Add lu-zero as mentor

### ISSUE THREAD

**Issue by lu-zero** [RustBeginners/awesome-rust-mentors#30]
### Luca Barbato ([@lu-zero](https://github.com/lu-zero))
* **Contact**: IRC (lu_zero on [freenode.net](http://webchat.freenode.net/?channels=%23rust-av&uio=d4)), [lu_zero](https://telegram.me/lu_zero) on Telegram
* **Spoken Languages**: English, Italian
* **Topics**: Multimedia, cargo, proc-macros, CLI

**Comment by yaahc** [comment]
Luca, do you have a language that you'd like us to italicize? We've been doing so for everyone's first language, but it is optional.

**Comment by lu-zero** [comment]
I do not have a favorite language, it is fine as is :)
