### ISSUE TITLE
Add Shady as mentor

### ISSUE THREAD

**Issue by shekohex** [RustBeginners/awesome-rust-mentors#4]
* **Preferred Name**: Shady Khalifa
* **Github Username or equivalent handle**: @shekohex on almost every website :)
* **Pronouns**: He/Him
* **Contact**: Twitter (@shekohex)
* **Spoken Languages**: **Arabic**, English
* **Topics**: Networking, FFI, CLI, Parsers, Development Tools, Web (Server-Side)

**Comment by yaahc** [comment]
I opened a PR to included these changes, lmk if everything looks good :D

**Comment by shekohex** [comment]
Great :+1: , Thank you!
