### ISSUE TITLE
Would it be possible to get exercism.io rust mentors via this place? 

### ISSUE THREAD

**Issue by a4z** [RustBeginners/awesome-rust-mentors#48]
Hi, 

I am currently doing the Rust track on exercism.io

I wait now since 3 days for the OK of a mentor to continue my track, this is not good.
Of course I can leaf the mentored way and unlock all exercises, what I will possible do, but in general, for people who would like to learn Rust this way faster mentor response would be great.

Since this place is about awesome rust mentors I thought it could not harm to add a note about the exercism.io problem here, and maybe this could be added as a possibility for awesome rust mentors to help people like me who use exercism to learn Rust.
Hope it's OK  that I opened this issue with this topic

**Comment by yaahc** [comment]
I'd be happy to!

Can I as what problem you're currently working on?

**Comment by yaahc** [comment]
Nevermind, I stalked down your problem and reviewed it. Looked great! Just drop another comment in here when your next solution is ready for review and which one it is and I'll take a look at it. This is making me think I should add `exercism.io` to my mentor topics so people know to ping me for review...

and maybe a section on general exercism review request via issues...

I'm so full of ideas!

**Comment by a4z** [comment]
just saw your review, thanks a lot Jane! 
yes, having mentioned exercism.io and mentors here, plus the possibility to ping, would be great!

**Comment by a4z** [comment]
is seems so far you are the only one with the exercism.io tag in the topic description. 
would be great to see more people having it!  hanging again for several days in the Q, no progress, 

how are you supposed to be pinged , @yaahc (or mentors in general) , DM via twitter?

**Comment by yaahc** [comment]
Commenting here or dming on Twitter both work. I didn't realize you had another solution up, sorry about that 😣

**Comment by a4z** [comment]
thanks! you can not do the whole rust mentoring on exercism alone! 
There should be > 30 mentors, but it seems most of them are not active (anymore), 
https://exercism.io/tracks/rust/mentors
it seems to me status messages how many exercises are in the Q do not change a lot over time. 
So I guess this is also a problem exercism has to think about ....

**Comment by undef1nd** [comment]
Hi @yaahc, I have absolutely the same issue: I submitted my last exercise a week ago or so, but it's still in the queue. Could you plz take a look at it once you have some time? Thanks! Looks like it'll take eternity to complete the Rust track 😆

**Comment by yaahc** [comment]
Yes, of course. I won't be able to check it for a couple days because I'm currently at a rust conference but I'll review them both as soon as I'm home.

**Comment by yaahc** [comment]
Okay, @undef1nd I did yours, but @a4z I'm having trouble finding your solution online. Did someone else get to it first? If not can you remind me what exercise you're on and what your username is?

**Comment by undef1nd** [comment]
Thanks, @yaahc , for the quick review. May I ping you in Twitter or here once I have the next one ready? 😊

**Comment by a4z** [comment]
LudwigStecher is reviewing my solution since yesterday, thanks a lot for caring @yaahc !

**Comment by yaahc** [comment]
@undef1nd yup! Twitter is probably better so you dont spam @a4z with notifications.
