### ISSUE TITLE
Cursed Code Counsellor

### ISSUE THREAD

**Issue by nvzqz** [RustBeginners/awesome-rust-mentors#6]
* **Preferred Name**: Nikolai Vazquez

* **Github Username or equivalent handle**: nvzqz

* **Pronouns**: he/him/his

* **Contact**: nikvzqz@gmail.com

* **Spoken Languages**: English, Spanish, German

* **Topics**: Learning Rust from nothing or experienced newcomers

* **Additional resources**: I maintain the Static Assertions crate and so I'd be happy to teach people how it works

**Comment by yaahc** [comment]
I opened a PR to included these changes, lmk if everything looks good :D

**Comment by sorenmortensen** [comment]
@nvzqz, could you please just confirm for me what your preferred spoken language is? Thanks

**Comment by nvzqz** [comment]
@sorenmortensen English
