### ISSUE TITLE
Mentee Application- New to Rust but not Programming

### ISSUE THREAD

**Issue by Michael-J-Ward** [RustBeginners/awesome-rust-mentors#64]
Preferred Name: Mike / Michael Ward [@Michael-J-Ward](https://github.com/Michael-J-Ward)

Github Handle: Michael-J-Ward
Pronouns: he / him
Contact: email / slack / hangouts / discord / any. I haven't actually used twitter until recently but [here](https://twitter.com/Michael_J_Ward)
Spoken Languages: English
Topics: For Rust specifically, I'm currently working through the rust book and exercism.io exercises. After i finish that I'd like to complete [Practical Networked Applications in Rust](https://github.com/pingcap/talent-plan/tree/master/rust) and find a way to contribute to open source projects. 

Such a cool thing to set up! Thank you @yaahc !

**Comment by Michael-J-Ward** [comment]
I realize now that I misread- *Mentor's* apply this way. *Mentee's* just reach out! Sorry for the confusion.

**Comment by yaahc** [comment]
Hehe no problem. And you're welcome! ❤️
