### ISSUE TITLE
Add rw as a mentor

### ISSUE THREAD

**Issue by rw** [RustBeginners/awesome-rust-mentors#65]
### Preferred Name ([@rw](https://github.com/rw))
* **Pronouns**: he/him
* **Contact**: Twitter (Direct Messages are open) [@robert_winslow](https://twitter.com/robert_winslow)
* **Spoken Languages**: English
* **Topics (General)**: Distributed systems, low-latency, testing, formal methods, Bayesian statistics, machine learning, deep learning, serialization.
* **Topics (Rust-specific)**: async/await, [FlatBuffers](https://github.com/google/flatbuffers), testing, minimizing heap allocations, lifetimes, traits, borrow-checker, API design.
* **Additional Resources**: Video of a [talk I presented at Mozilla HQ on FlatBuffers in Rust](https://www.youtube.com/watch?v=YsiQDX20lXI).

**Comment by yaahc** [comment]
This looks great. I'm currently at a rust conference but when I get home on Sunday I'll merge this.
