### ISSUE TITLE
Add Phil as a mentor

### ISSUE THREAD

**Issue by flip1995** [RustBeginners/awesome-rust-mentors#66]
### Phil Krones ([@flip1995](https://github.com/flip1995))
* **Pronouns**: he/him
* **Contact**: GitHub ([@flip1995](https://github.com/flip1995)), E-Mail (hello@philkrones.com), Discord ([flip1995#2683](https://discordapp.com/users/618807455651987476); not that active there)
* **Spoken Languages**: German, English (German is my first language, but I don't really have a "preferred" one)
* **Topics**: Beginners, Clippy, Lints, Diagnostics

**Comment by yaahc** [comment]
Hi Phil! this looks good. I'm currently at a rust conference but when I get home on Sunday I'll merge this.
