### ISSUE TITLE
Add Mara as a mentor

### ISSUE THREAD

**Issue by m-ou-se** [RustBeginners/awesome-rust-mentors#7]
* **Preferred Name**: Mara Bos
* **Github Username or equivalent handle**: @m-ou-se
* **Pronouns**: she/her
* **Contact**: E-mail: rust@m-ou.se, or Twitter: @m_ou_se, or IRC: M-ou-se on Freenode
* **Spoken Languages**: English, Dutch
* **Topics**: Embedded, CLI, math, proc-macro, Linux, undefined behaviour, FFI, lifetimes
* **Additional resources**: -

**Comment by yaahc** [comment]
I opened a PR to included these changes, lmk if everything looks good :D

**Comment by m-ou-se** [comment]
Oh, I just edited the issue to add 'lifetimes' to the list of topics. Other than that, looks good ^^
