### ISSUE TITLE
Fix @phaazon Display Name on Site

### ISSUE THREAD

**Issue by deg4uss3r** [RustBeginners/awesome-rust-mentors#72]
Looks like @phaazon's name isn't displaying right on the site (#71): ![](https://imgur.com/ZNPRxfe.png)

**Comment by phaazon** [comment]
![](https://phaazon.net/media/uploads/chloe.gif)

**Comment by phaazon** [comment]
![](http://giphygifs.s3.amazonaws.com/media/fhLgA6nJec3Cw/giphy.gif)

**Comment by yaahc** [comment]
ooh shit ty

**Comment by deg4uss3r** [comment]
For refence I'm on Firefox Nightly `71.0a1 (2019-09-23) (64-bit)`

**Comment by phaazon** [comment]
OMG @yaahc you’re fast.
